server:
  applicationConnectors:
    - type: https
      port: 9200
      keyStorePath: /run/secrets/keystore
      keyStorePassword: ${KEYSTORE_PASSWORD}
      validateCerts: false
  adminConnectors:
    - type: http
      port: 9201

kafka:
    hosts: ${KAFKA_BROKER_URL}
    clientId: dashbase
    kafkaProps:
      compression.type: lz4
      security.protocol: SSL
      ssl.truststore.location: /run/secrets/keystore
      ssl.truststore.password: ${KEYSTORE_PASSWORD}
      ssl.keystore.location: /run/secrets/keystore
      ssl.keystore.password: ${KEYSTORE_PASSWORD}
      ssl.key.password: ${KEYSTORE_PASSWORD}

parser:
  type: filebeat
  params:
    useTimestampInLogMessage: true

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/proxy.log
        archive: true
        archivedLogFilenamePattern: /app/logs/proxy-%d-%i.log.gz
        archivedFileCount: 9
        timeZone: UTC
        maxFileSize: 100MB
      - type: console
