server:
  applicationConnectors:
    - type: http
      port: 9200
      keyStorePath: /run/secrets/keystore
      keyStorePassword: ${KEYSTORE_PASSWORD}
      validateCerts: false
  adminConnectors:
    - type: http
      port: 9201

kafka:
    hosts: ${KAFKA_BROKER_URL}
    clientId: dashbase
    kafkaProps:
      compression.type: lz4

# Specify the output format
# 'raw': pass the raw input JSON
# 'avro': parse the filebeat JSON into Avro DashbaseEvent and sends its binary
outputFormat: avro

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/proxy.log
        archive: true
        archivedLogFilenamePattern: /app/logs/proxy-%d-%i.log.gz
        archivedFileCount: 9
        timeZone: UTC
        maxFileSize: 100MB
      - type: console
