configs:
  proxy_config:
    file: ./config/proxy/config.yml
networks:
  dashbase_backend:
    external: true
services:
  proxy:
    image: dashbase/proxy:latest
    depends_on:
      - kafka
    networks:
      - dashbase_backend
    deploy:
      replicas: 1
    configs:
      - source: proxy_config
        target: /app/config.yml
    ports:
      - "9200:9200"
    command: ["server", "/app/config.yml"]
    volumes:
      - logs:/app/logs:rw
    env_file:
      - env
version: '3.4'
volumes:
  logs:
    external: true
