dashbase:
  # cluster configuration
  cluster:
    url: zk://${ZOOKEEPER_URL}/dashbase/docker/_system

  # following configurations only applies to server mode

  # base directory
  baseDir: /dashbase/index/_system

  # indexing parameters (optional)
  indexer:
    minBufferedSizeMB: 50
    maxBufferDelayInSec: 10

  retention:
    expirationHandler:
      params:
      type: purge
    numDays: 7

  parser:
    type: _system

server:
  applicationConnectors:
    - type: https
      port: ${PORT}
      keyStorePath: /app/keystore
      keyStorePassword: ${KEYSTORE_PASSWORD}
      validateCerts: false
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: ${ADMINPORT}
  requestLog:
    appenders: []
metrics:
  reporters:
    - type: dashbase
      url: ${MONITOR_URL}
      includes:
        - ^jvm.*$
        - ^dashbase.*$
      useRegexFilters: true
      frequency: 5 seconds
logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/system-monitor.log
        archive: true
        archivedLogFilenamePattern: /app/logs/system-monitor-%d.log
        archivedFileCount: 9
        timeZone: UTC
      - type: dashbase
        url: ${MONITOR_URL}
        timeZone: UTC
      - type: console
