applicationId: warg-${KAFKA_TOPIC}

kafkaBootstrapServers: kafka:9092

kafkaProps:
  security.protocol: SSL
  ssl.truststore.location: /run/secrets/keystore
  ssl.truststore.password: ${KEYSTORE_PASSWORD}
  ssl.keystore.location: /run/secrets/keystore
  ssl.keystore.password: ${KEYSTORE_PASSWORD}
  ssl.key.password: ${KEYSTORE_PASSWORD}

topics: ${KAFKA_TOPIC}

parser:
  type: filebeat

outputTopicSuffix: _avro

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/warg.log
        archive: true
        archivedLogFilenamePattern: /app/logs/warg-%d-%i.log.gz
        archivedFileCount: 9
        timeZone: UTC
        maxFileSize: 100MB
      - type: console
