applicationId: warg-${KAFKA_TOPIC}

kafkaBootstrapServers: ${KAFKA_BROKER_URL}

kafkaProps:
  compression.type: lz4

topics: ${KAFKA_TOPIC}

parser:
  type: filebeat

outputTopicSuffix: _avro

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/${KAFKA_TOPIC}-warg.log
        archive: true
        archivedLogFilenamePattern: /app/logs/${KAFKA_TOPIC}-warg-%d-%i.log.gz
        archivedFileCount: 9
        timeZone: UTC
        maxFileSize: 100MB
      - type: console
