applicationId: warg-monitor

kafkaBootstrapServers: monitor_kafka:9092

kafkaProps:
  compression.type: lz4

topics: _logs,_metrics

outputTopicSuffix: _avro

useLocalTimestamp: true

parser:
  type: filebeat

fieldsToDrop:
  ".*":
    - offset
  "_metrics":
    - ".*units$"

logging:
  level: INFO
  appenders:
      - type: console
