applicationId: warg-monitor

kafkaBootstrapServers: monitor_kafka:9092

kafkaProps:
  security.protocol: SSL
  ssl.truststore.location: /run/secrets/keystore
  ssl.truststore.password: ${KEYSTORE_PASSWORD}
  ssl.keystore.location: /run/secrets/keystore
  ssl.keystore.password: ${KEYSTORE_PASSWORD}
  ssl.key.password: ${KEYSTORE_PASSWORD}


topics: _logs,_metrics

outputTopicSuffix: _avro

useLocalTimestamp: true

parser:
  type: filebeat

logging:
  level: INFO
  appenders:
      - type: console
