zipkinFactory:
  enabled: true
  collector: http
  baseUrl: ${ZIPKIN_URL}
  servicePort: ${PORT}
  serviceName: "${TABLE_NAME}"

dashbase:
  baseDir: /dashbase/index
  readerCacheSize: 10000

  firehose:
    type: file
    params:
      file: /data/nginx_sample.json

  cluster:
    url: zk://${ZOOKEEPER_URL}/dashbase/docker/${TABLE_NAME}

  indexer:
    numIndexingThreads: 3
    #maxNumConcurrentBuilding: 3
    maxBufferDelayInSec: 90

  retention:
    numDays: 7

  parser:
    type: json


server:
  applicationConnectors:
    - type: https
      port: ${PORT}
      keyStorePath: /run/secrets/keystore
      keyStorePassword: ${KEYSTORE_PASSWORD}
      validateCerts: false
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: ${ADMINPORT}

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/${TABLE_NAME}-${DASHBASE_PARTITION}-table.log
        archive: true
        archivedLogFilenamePattern: /app/logs/${TABLE_NAME}-${DASHBASE_PARTITION}-table-%d-%i.log.gz
        archivedFileCount: 5
        maxFileSize: 100MB
        timeZone: UTC
      - type: console
