# Should be run on all hosts
metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - core
    - diskio
    #- socket
  processes: ['.*java.*'] # only monitor java processes
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  filesystem.ignore_types: [nfs, smbfs, autofs, tmpfs, proc, overlay]

output.console:
  enabled: false # change to true for debugging
  pretty: true

output.kafka:
  hosts: ['monitor_kafka:9092']
  topic: _metrics

  ssl:
    certificate_authorities: ["/run/secrets/ca_cert_pem"]
    certificate: /run/secrets/client_cert_pem
    key: /run/secrets/client_key_pem
    # CN of the above cert must be the domain of Kafka broker.
    # Disabling verification mode to skip the above domain check.
    verification_mode: none
