# a single dashbase table
# We use zookeeper for service discovery so no need to define a service for table
# We define a service here for ease of debugging.
---
apiVersion: v1
kind: Service
metadata:
  name: dashbase-api
  namespace: dashbase
spec:
  ports:
    - port: 9876
      name: table-port
  selector:
    app: dashbase-api
  clusterIP: None

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dashbase-api
  namespace: dashbase
spec:
  serviceName: "quickstart-api"
  replicas: 1
  template:
    metadata:
      labels:
        app: dashbase-api
    spec:
      imagePullSecrets:
      - name: docker-image-secret
      containers:
      - name: quickstart-api
        image: dashbase/api:1.0.0-rc14
        command: ['/dashbase-api-1.0.0-rc14/bin/dashbase-api', 'server', '/config/api.yml']
        env:
        - name: ZOOKEEPER_URL
          value: "zookeeper.zookeeper.svc.cluster.local:2181"
        - name: PORT
          value: "9876"
        - name: ADMINPORT
          value: "9976"
        - name: JAVA_OPTS
          value: "-Xmx1g -Xms512m -XX:NewSize=512m"
        ports:
        - containerPort: 9876
        volumeMounts:
        - name: dashbase-config
          mountPath: /config
        - name: data
          mountPath: /app
      volumes:
      - name: dashbase-config
        configMap:
          name: dashbase-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 4Gi


