dashbaseURL: ${API_URL}

notifiers:
  - name: Console
    type: console
#  - name: Slack
#    type: slack
#    url:

alerts:
  - name: api_cpu_percent
    sql: "SELECT avg('jvm.cpu.usage.percent.value') as 'value' FROM _metrics WHERE service='api' LIMIT 0"
    description: "Dashbase API CPU usage percent"
    times: 5
    type: higher_than
    threshold: 80
    periodInSeconds: 300

  - name: api_heap_percent
    sql: "SELECT avg('jvm.memory.heap.usage.value') as 'value' FROM _metrics WHERE service='api' LIMIT 0"
    description: "Dashbase API heap usage percent"
    times: 5
    type: higher_than
    threshold: 0.80
    periodInSeconds: 300

## alerts for internal tables
  - name: table_metrics_cpu_percent
    sql: "SELECT avg('jvm.cpu.usage.percent.value') as 'value' FROM _metrics WHERE service='table' AND table_name='_metrics' LIMIT 0"
    description: "_metrics table CPU usage percent"
    times: 5
    type: higher_than
    threshold: 80
    periodInSeconds: 300

  - name: table_metrics_heap_percent
    sql: "SELECT avg('jvm.memory.heap.usage.value') as 'value' FROM _metrics WHERE service='table' AND table_name='_metrics' LIMIT 0"
    description: "_metrics table heap usage percent"
    times: 5
    type: higher_than
    threshold: 0.80
    periodInSeconds: 300

  - name: table_logs_cpu_percent
    sql: "SELECT avg('jvm.cpu.usage.percent.value') as 'value' FROM _metrics WHERE service='table' AND table_name='_logs' LIMIT 0"
    description: "_logs table CPU usage percent"
    times: 5
    type: higher_than
    threshold: 80
    periodInSeconds: 300

  - name: table_logs_heap_percent
    sql: "SELECT avg('jvm.memory.heap.usage.value') as 'value' FROM _metrics WHERE service='table' AND table_name='_logs' LIMIT 0"
    description: "_logs table heap usage percent"
    times: 5
    type: higher_than
    threshold: 0.80
    periodInSeconds: 300

  - name: table_traces_cpu_percent
    sql: "SELECT avg('jvm.cpu.usage.percent.value') as 'value' FROM _metrics WHERE service='table' AND table_name='_traces' LIMIT 0"
    description: "_traces table CPU usage percent"
    times: 5
    type: higher_than
    threshold: 80
    periodInSeconds: 300

  - name: table_traces_heap_percent
    sql: "SELECT avg('jvm.memory.heap.usage.value') as 'value' FROM _metrics WHERE service='table' AND table_name='_traces' LIMIT 0"
    description: "_traces table heap usage percent"
    times: 5
    type: higher_than
    threshold: 0.80
    periodInSeconds: 300

  - name: monitor_tables_disk_percent
    sql: "SELECT avg('dashbase.disk.available.bytes.percent.value') as 'value' FROM _metrics WHERE service='table' AND table_name='_metrics' LIMIT 0"
    description: "internal monitor tables disk usage percent"
    times: 5
    type: lower_than
    threshold: 10.00
    periodInSeconds: 300

server:
  applicationConnectors:
    - type: https
      port: ${PORT}
      keyStorePath: /run/secrets/keystore
      keyStorePassword: ${KEYSTORE_PASSWORD}
      validateCerts: false
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: ${ADMINPORT}
  requestLog:
    appenders: []

logging:
  level: INFO
  appenders:
    - type: console
