metricbeat.modules:

- module: dropwizard
  metricsets: ["collector"]
  period: 10s
  metrics_path: /admin/metrics
  namespace: dashbase
  fields:
    service: table
    table_name: ${TABLE_NAME}
    partition: '"${PARTITION}"'

output.kafka:
  hosts: ['monitor_kafka:9092']
  topic: _metrics