metricbeat.modules:

- module: dropwizard
  metricsets: ["collector"]
  period: 10s
  hosts: ["${HOST}:8081"]
  metrics_path: /metrics
  namespace: dashbase
  fields:
    service: warg

output.kafka:
  hosts: ['monitor_kafka:9092']
  topic: _metrics
