zipkinFactory:
  enabled: true
  collector: http
  baseUrl: ${ZIPKIN_URL}
  servicePort: ${PORT}
  serviceName: "table/${TABLE_NAME}"

dashbase:
  # cluster configuration
  cluster:
    url: zk://zookeeper:2181/dashbase/docker/${TABLE_NAME}

  # following configurations only applies to server mode

  # base directory
  baseDir: /dashbase/index/${TABLE_NAME}

  # indexing parameters (optional)
  indexer:
    minBufferedSizeMB: 50
    maxBufferDelayInSec: 10
    storeRawInput: ${STORE_RAW_INPUT}

  retention:
    expirationHandler:
      params:
      type: purge
    numDays: 7

  firehose:
      type: kafka_10
      params:
        hosts: monitor_kafka:9092
        groupId: dashbase
        topic: ${KAFKA_TOPIC}_avro
        partitions: 0
        kafkaProps:
          security.protocol: SSL
          ssl.truststore.location: /run/secrets/keystore
          ssl.truststore.password: ${KEYSTORE_PASSWORD}
          ssl.keystore.location: /run/secrets/keystore
          ssl.keystore.password: ${KEYSTORE_PASSWORD}
          ssl.key.password: ${KEYSTORE_PASSWORD}

  parser:
    type: avro_native


server:
  applicationConnectors:
    - type: https
      port: ${PORT}
      keyStorePath: /run/secrets/keystore
      keyStorePassword: ${KEYSTORE_PASSWORD}
      validateCerts: false
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: ${ADMINPORT}
  requestLog:
    appenders: []

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/${TABLE_NAME}-0-table.log
        archive: true
        archivedLogFilenamePattern: /app/logs/${TABLE_NAME}-0-table-%d-%i.log.gz
        archivedFileCount: 5
        maxFileSize: 100MB
        timeZone: UTC
      - type: console
