name: filebeat_dashbase

filebeat.prospectors:
- type: log
  paths: [/app/kafka/logs/*.log]
  fields:
    service: kafka
    log_type: log4j
    log_pattern: "[%d] %p %m (%c)%n"
  multiline.pattern: '^[^\[]'
  multiline.negate: false
  multiline.match: after

- type: log
  paths: [/app/logs/proxy.log]
  fields:
    service: proxy
    log_type: logback
    log_pattern: "%-5p [%d{ISO8601}] %c: %m%n"
  multiline.pattern: '^[^A-Z]|^$'
  multiline.negate: false
  multiline.match: after

- type: log
  paths: [/app/logs/dashbase-api.log]
  fields:
    service: api
    log_type: logback
    log_pattern: "%-5p [%d{ISO8601}] %c: %m%n"
  multiline.pattern: '^[^A-Z]|^$'
  multiline.negate: false
  multiline.match: after

- type: log
  paths: [/app/logs/dashbase-web.log]
  fields:
    service: web
    log_type: logback
    log_pattern: "%-5p [%d{ISO8601}] %c: %m%n"
  multiline.pattern: '^[^A-Z]|^$'
  multiline.negate: false
  multiline.match: after

- type: log
  paths: [/app/logs/*-warg.log]
  fields:
    service: warg
    log_type: logback
    log_pattern: "%-5p [%d{ISO8601}] %c: %m%n"
  multiline.pattern: '^[^A-Z]|^$'
  multiline.negate: false
  multiline.match: after

- type: log
  paths: [/app/logs/*-table.log]
  fields:
    service: table
    log_type: logback
    log_pattern: "%-5p [%d{ISO8601}] %c: %m%n"
  multiline.pattern: '^[^A-Z]|^$'
  multiline.negate: false
  multiline.match: after

output.kafka:
  hosts: ['monitor_kafka:9092']
  topic: _logs
