zipkinFactory:
  enabled: true
  collector: http
  baseUrl: ${ZIPKIN_URL}
  servicePort: ${PORT}
  serviceName: "table"

dashbase:
  baseDir: /dashbase/index
  readerCacheSize: 10000

  firehose:
      type: kafka_10
      params:
        hosts: kafka:9092
        groupId: ${KAFKA_GROUPID}
        topic: ${KAFKA_TOPIC}_avro
        partitions: "${KAFKA_PARTITIONS}"
        kafkaProps:
          security.protocol: SSL
          ssl.truststore.location: /run/secrets/keystore
          ssl.truststore.password: ${KEYSTORE_PASSWORD}
          ssl.keystore.location: /run/secrets/keystore
          ssl.keystore.password: ${KEYSTORE_PASSWORD}
          ssl.key.password: ${KEYSTORE_PASSWORD}

  cluster:
    url: zk://${ZOOKEEPER_URL}/dashbase/docker/table

  indexer:
    numIndexingThreads: 3
    #maxNumConcurrentBuilding: 3
    maxBufferDelayInSec: 90

  retention:
    numDays: 7

  parser:
    type: avro_native

server:
  applicationConnectors:
    - type: https
      port: ${PORT}
      keyStorePath: /run/secrets/keystore
      keyStorePassword: ${KEYSTORE_PASSWORD}
      validateCerts: false
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: ${ADMINPORT}
metrics:
  reporters:
    - type: dashbase
      url: ${MONITOR_URL}
      includes:
        - ^jvm.*$
        - ^dashbase.*$
      useRegexFilters: true
      frequency: 5 seconds

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/dashbase-table.log
        archive: true
        archivedLogFilenamePattern: /app/logs/dashbase-table-%d.log
        archivedFileCount: 9
        timeZone: UTC
      - type: dashbase
        url: ${MONITOR_URL}
        timeZone: UTC
      - type: console
