zipkinFactory:
  enabled: true
  collector: http
  baseUrl: ${ZIPKIN_URL}
  servicePort: ${PORT}
  serviceName: "web"

server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  applicationContextPath: /
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: ${ADMINPORT}

website:
  cdn: "http://cdn.domain.com"
  domain: "http://www.domain.com"
  name: "Dashbase Web"
  renderings:
    - table: "_logs"
      kind: "log4j"

backend:
  host: ${API_HOST}
  port: ${API_PORT}

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: /app/logs/dashbase-web.log
        archive: true
        archivedLogFilenamePattern: /app/logs/dashbase-web-%d.log
        archivedFileCount: 9
        timeZone: UTC
      - type: console
